/* ==========================================================================
   Adam's Sports Dashboard — Tournament Engine
   --------------------------------------------------------------------------
   Big tournaments (Rugby World Cup, Six Nations, Leinster Schools Cup…) get
   their own spotlight section + nav tab that appears automatically as the
   tournament approaches, stays pinned while it's on, lingers for a short
   recap, then retires itself. Entirely data-driven from data/tournaments.json
   (generated by scripts/fetch_tournaments.mjs from scripts/tournaments.config.json)
   — adding a tournament never requires touching this file.

   Phases:
     far   → not fetched, not rendered (fetcher skips it entirely)
     soon  → countdown hero, fixtures listed
     live  → LIVE treatment, results + remaining fixtures
     recap → "that's a wrap" hero, final results
     past  → removed from the page

   QA / time-travel: append ?tdate=2027-10-05 to preview any date.
   ========================================================================== */
(function () {
  "use strict";

  var DAY_MS = 86400000;

  /* ---------- time ------------------------------------------------------ */

  // Allow ?tdate=YYYY-MM-DD to simulate another date. This makes a feature
  // that is invisible for months of the year genuinely testable.
  function tournamentNow() {
    try {
      var q = new URLSearchParams(location.search).get("tdate");
      if (q) {
        var d = new Date(/^\d{4}-\d{2}-\d{2}$/.test(q) ? q + "T12:00:00Z" : q);
        if (!isNaN(d)) return d;
      }
    } catch (e) { /* no-op */ }
    return new Date();
  }

  function startOf(t) { return new Date(t.start + "T00:00:00Z"); }
  function endOf(t) { return new Date(t.end + "T23:59:59Z"); }

  // Mirror of phaseOf() in scripts/fetch_tournaments.mjs — keep the two in sync.
  function tournamentPhase(t, now) {
    now = now || tournamentNow();
    var s = startOf(t).getTime();
    var e = endOf(t).getTime();
    var lead = (t.lead_days == null ? 60 : t.lead_days) * DAY_MS;
    var recap = (t.recap_days == null ? 10 : t.recap_days) * DAY_MS;
    var n = now.getTime();
    if (n < s - lead) return "far";
    if (n < s) return "soon";
    if (n <= e) return "live";
    if (n <= e + recap) return "recap";
    return "past";
  }

  // The tournaments that should currently own a section, most urgent first.
  function visibleTournaments(all) {
    var list = (all && all.tournaments && all.tournaments.tournaments) || [];
    var now = tournamentNow();
    return list
      .map(function (t) { return { t: t, phase: tournamentPhase(t, now) }; })
      .filter(function (x) { return x.phase === "soon" || x.phase === "live" || x.phase === "recap"; })
      .sort(function (a, b) { return startOf(a.t) - startOf(b.t); });
  }

  /* ---------- helpers --------------------------------------------------- */

  function esc(s) {
    return typeof escapeHtml === "function"
      ? escapeHtml(s)
      : String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
          return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
        });
  }

  function sectionId(t) { return "t-" + t.id; }

  function daysUntil(target, now) {
    return Math.ceil((target.getTime() - now.getTime()) / DAY_MS);
  }

  function longDate(d) {
    try {
      return d.toLocaleDateString("en-IE", { weekday: "short", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
    } catch (e) { return d.toISOString().slice(0, 10); }
  }

  function nextFixture(t, now) {
    var best = null;
    (t.fixtures || []).forEach(function (m) {
      if (!m.date) return;
      var d = new Date(m.date);
      if (isNaN(d) || d < now) return;
      if (!best || d < new Date(best.date)) best = m;
    });
    return best;
  }

  // A match kicking off within ±3h counts as "on right now".
  function liveMatches(t, now) {
    return [].concat(t.results || [], t.fixtures || []).filter(function (m) {
      if (!m.date) return false;
      var d = new Date(m.date).getTime();
      return Math.abs(d - now.getTime()) < 3 * 3600 * 1000;
    });
  }

  function isFav(t, name) {
    return (t.fav_teams || []).some(function (f) {
      return String(name || "").toLowerCase().indexOf(String(f).toLowerCase()) >= 0;
    });
  }

  function favNextFixture(t, now) {
    var fav = (t.fixtures || []).filter(function (m) {
      if (!m.date || new Date(m.date) < now) return false;
      return isFav(t, m.home) || isFav(t, m.away);
    });
    fav.sort(function (a, b) { return String(a.date).localeCompare(String(b.date)); });
    return fav[0] || null;
  }

  /* ---------- hero ------------------------------------------------------ */

  function heroHtml(t, phase, now) {
    var start = startOf(t);
    var end = endOf(t);
    var teamLine = (t.fav_teams || []).length
      ? '<span class="tourn-fav">Watching ' + esc(t.fav_teams.join(" · ")) + "</span>"
      : "";

    if (phase === "soon") {
      var days = Math.max(0, daysUntil(start, now));
      var weeks = Math.floor(days / 7);
      var sub = days === 0 ? "Kicks off today" :
                days === 1 ? "Kicks off tomorrow" :
                weeks >= 2 ? "About " + weeks + " weeks away" : days + " days away";
      var fav = favNextFixture(t, now) || nextFixture(t, now);
      return '' +
        '<div class="tourn-hero tourn-hero--soon">' +
          '<div class="tourn-hero-main">' +
            '<span class="tourn-pill tourn-pill--soon">Coming up</span>' +
            '<div class="tourn-count"><strong>' + days + '</strong><span>' + (days === 1 ? "day" : "days") + " to go" + "</span></div>" +
            '<p class="tourn-hero-sub">' + esc(sub) + " · starts " + esc(longDate(start)) + "</p>" +
            (fav ? '<p class="tourn-hero-line">First up: <strong>' + esc(fav.home) + "</strong> v <strong>" + esc(fav.away) + "</strong></p>" : "") +
            teamLine +
          "</div>" +
        "</div>";
    }

    if (phase === "live") {
      var onNow = liveMatches(t, now);
      var nxt = favNextFixture(t, now) || nextFixture(t, now);
      var dayNo = Math.floor((now - start) / DAY_MS) + 1;
      var totalDays = Math.max(1, Math.round((end - start) / DAY_MS) + 1);
      var pct = Math.min(100, Math.max(0, Math.round((dayNo / totalDays) * 100)));
      return '' +
        '<div class="tourn-hero tourn-hero--live">' +
          '<div class="tourn-hero-main">' +
            '<span class="tourn-pill tourn-pill--live"><span class="tourn-dot" aria-hidden="true"></span>Under way</span>' +
            "<p class=\"tourn-hero-sub\">Day " + dayNo + " of " + totalDays + " · finishes " + esc(longDate(end)) + "</p>" +
            '<div class="tourn-progress" role="img" aria-label="Tournament ' + pct + '% complete"><span style="width:' + pct + '%"></span></div>' +
            (onNow.length
              ? '<p class="tourn-hero-line tourn-hero-line--hot">🔴 ' + onNow.length + (onNow.length === 1 ? " match" : " matches") + " on right now</p>"
              : nxt ? '<p class="tourn-hero-line">Next: <strong>' + esc(nxt.home) + "</strong> v <strong>" + esc(nxt.away) + "</strong></p>" : "") +
            teamLine +
          "</div>" +
        "</div>";
    }

    // recap
    var played = (t.results || []).length;
    return '' +
      '<div class="tourn-hero tourn-hero--recap">' +
        '<div class="tourn-hero-main">' +
          '<span class="tourn-pill tourn-pill--recap">That\'s a wrap</span>' +
          '<p class="tourn-hero-sub">Finished ' + esc(longDate(end)) + " · " + played + (played === 1 ? " match" : " matches") + " played</p>" +
          '<p class="tourn-hero-line">Full results below — this section disappears shortly.</p>' +
          teamLine +
        "</div>" +
      "</div>";
  }

  /* ---------- section scaffolding -------------------------------------- */

  function buildSection(t) {
    var sec = document.createElement("section");
    sec.className = "section section--tourn";
    sec.id = sectionId(t);
    sec.dataset.tournament = t.id;
    sec.innerHTML = '' +
      '<div class="section-head section-head--page">' +
        '<div class="section-title">' +
          '<span class="accent-bar accent-bar--tourn"></span>' +
          "<h2>" + esc(t.emoji || "🏆") + " " + esc(t.label) + "</h2>" +
        "</div>" +
        (t.blurb ? '<p class="section-sub">' + esc(t.blurb) + "</p>" : "") +
      "</div>" +
      '<div class="tourn-hero-slot"></div>' +
      '<section class="card card-wide" id="panel-' + esc(sectionId(t)) + '">' +
        '<div class="card-head"><h3>' + esc(t.emoji || "🏆") + " Fixtures &amp; results</h3></div>" +
        '<div class="panel-body" id="' + esc(sectionId(t)) + '-body"></div>' +
      "</section>";
    return sec;
  }

  function buildTab(t) {
    var a = document.createElement("a");
    a.className = "nav-tab nav-tab--tourn";
    a.dataset.target = sectionId(t);
    a.href = "#" + sectionId(t);
    a.setAttribute("role", "tab");
    a.setAttribute("aria-selected", "false");
    a.innerHTML = '<span aria-hidden="true">' + esc(t.emoji || "🏆") + "</span> " + esc(shortLabel(t.label));
    return a;
  }

  // Nav tabs are tight on mobile — drop the year and any trailing noise.
  function shortLabel(label) {
    return String(label).replace(/\s+(19|20)\d{2}\b/, "").trim();
  }

  /* ---------- render ---------------------------------------------------- */

  function renderTournaments(all) {
    var main = document.querySelector("main") ||
               (document.getElementById("rugby") && document.getElementById("rugby").parentNode);
    var tabsWrap = document.getElementById("nav-tabs");
    if (!main) return;

    var active = visibleTournaments(all);
    var wanted = {};
    active.forEach(function (x) { wanted[sectionId(x.t)] = true; });

    // 1. Retire anything that has aged out (or was removed from the config).
    Array.prototype.slice.call(document.querySelectorAll("section.section--tourn")).forEach(function (sec) {
      if (!wanted[sec.id]) sec.remove();
    });
    if (tabsWrap) {
      Array.prototype.slice.call(tabsWrap.querySelectorAll(".nav-tab--tourn")).forEach(function (tab) {
        if (!wanted[tab.dataset.target]) tab.remove();
      });
    }

    // 2. Create / update the live set. Idempotent: rerenderAll() may run many times.
    var now = tournamentNow();
    active.forEach(function (x) {
      var t = x.t, phase = x.phase, id = sectionId(t);
      var sec = document.getElementById(id);
      if (!sec) {
        sec = buildSection(t);
        var news = document.getElementById("news");
        if (news && news.parentNode === main) main.insertBefore(sec, news);
        else main.appendChild(sec);
      }
      sec.dataset.phase = phase;

      var slot = sec.querySelector(".tourn-hero-slot");
      if (slot) slot.innerHTML = heroHtml(t, phase, now);

      // Reuse the existing rugby renderer so tournament tables are visually
      // identical to the rest of the site (watch chips, reminders, share…).
      if (typeof renderRugbyMatches === "function") {
        renderRugbyMatches(id + "-body", { results: t.results || [], fixtures: t.fixtures || [] },
          t.label, { withLogos: (t.source || "").indexOf("espn") === 0, favTeams: t.fav_teams || [] });
      }

      // Early in a tournament there are no results yet, and months out the
      // fixtures often aren't published at all. Collapse the dead column
      // instead of showing a half-empty table with an em-dash in it.
      var body = document.getElementById(id + "-body");
      if (body) {
        var nRes = (t.results || []).length;
        var nFix = (t.fixtures || []).length;
        if (!nRes && !nFix) {
          body.dataset.empty = "both";
          body.innerHTML =
            '<p class="tourn-empty">📅 Fixtures for <strong>' + esc(t.label) + "</strong> haven't been " +
            "published yet — they'll appear here automatically as soon as they're announced.</p>";
        } else {
          body.dataset.empty = !nRes ? "results" : !nFix ? "fixtures" : "";
        }
      }

      if (tabsWrap && !tabsWrap.querySelector('.nav-tab--tourn[data-target="' + id + '"]')) {
        var news2 = tabsWrap.querySelector('[data-target="news"]');
        var tab = buildTab(t);
        if (news2) tabsWrap.insertBefore(tab, news2);
        else tabsWrap.appendChild(tab);
        // A brand-new tab shifts every offset the indicator depends on.
        if (typeof window.__refreshNavIndicator === "function") {
          requestAnimationFrame(window.__refreshNavIndicator);
        }
      }
    });
  }

  /* ---------- integration hooks ---------------------------------------- */

  // Feed items so tournaments also surface in Latest / Upcoming / search.
  function tournamentMatches(all) {
    var out = [];
    visibleTournaments(all).forEach(function (x) {
      var t = x.t;
      (t.results || []).forEach(function (m) { out.push({ m: m, t: t, isResult: true }); });
      (t.fixtures || []).forEach(function (m) { out.push({ m: m, t: t, isResult: false }); });
    });
    return out;
  }

  window.TournamentEngine = {
    now: tournamentNow,
    phase: tournamentPhase,
    visible: visibleTournaments,
    matches: tournamentMatches,
    sectionId: sectionId,
    render: renderTournaments,
  };

  // app.js calls these directly.
  window.renderTournaments = renderTournaments;
})();
