#!/usr/bin/env python3
"""Freshness alert for refresh.yml.

Checks every data/*.json file for a `generated_at` (or `fetched_at`)
timestamp. If any are older than STALE_HOURS, opens (or appends a comment
to) a GitHub issue labeled `data-freshness`. If everything is fresh, any
open freshness issue is auto-closed with a green comment.

Designed to run inside GitHub Actions where GITHUB_TOKEN and GITHUB_REPOSITORY
are pre-populated. Exits 0 always so it never fails the workflow.
"""
from __future__ import annotations
import datetime as _dt
import json
import os
import subprocess
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"
STALE_HOURS = 24
LABEL = "data-freshness"


def gh(*args, input_text: str | None = None) -> tuple[int, str]:
    res = subprocess.run(
        ["gh", *args],
        input=input_text,
        capture_output=True, text=True, check=False,
    )
    return res.returncode, (res.stdout or "") + (res.stderr or "")


def main() -> int:
    if not DATA.exists():
        print("no data/ dir — nothing to check")
        return 0

    now = _dt.datetime.now(_dt.timezone.utc)
    stale: list[str] = []
    fresh: list[str] = []
    missing: list[str] = []

    for f in sorted(DATA.glob("*.json")):
        if f.name.startswith("_"):
            continue
        try:
            doc = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            stale.append(f"{f.name} (bad JSON: {e})")
            continue
        ts = doc.get("generated_at") or doc.get("fetched_at")
        if not ts:
            missing.append(f.name)
            continue
        try:
            d = _dt.datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
        except ValueError:
            stale.append(f"{f.name} (unparseable timestamp: {ts})")
            continue
        if d.tzinfo is None:
            d = d.replace(tzinfo=_dt.timezone.utc)
        hours = (now - d).total_seconds() / 3600
        if hours > STALE_HOURS:
            stale.append(f"{f.name} — {hours:.1f}h old (last: {ts})")
        else:
            fresh.append(f"{f.name} — {hours:.1f}h")

    print(f"fresh: {len(fresh)} · stale: {len(stale)} · missing-ts: {len(missing)}")

    # Need gh available + a token. If not, just log and exit.
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        print("no GITHUB_TOKEN/REPOSITORY env — skipping issue management")
        return 0

    # Find existing freshness issue (if any)
    code, out = gh("issue", "list", "--repo", repo, "--label", LABEL, "--state", "open", "--json", "number,title")
    open_issues: list[dict] = []
    if code == 0:
        try:
            open_issues = json.loads(out or "[]")
        except json.JSONDecodeError:
            open_issues = []

    if stale:
        body = (
            "🚨 **Data freshness alert** — one or more `data/*.json` files are >"
            f"{STALE_HOURS}h old.\n\n"
            "### Stale\n" + "\n".join(f"- `{s}`" for s in stale) + "\n\n"
            "### Fresh\n" + ("\n".join(f"- `{s}`" for s in fresh) if fresh else "_(none)_") + "\n\n"
            "Auto-generated by `scripts/check_freshness.py` in `refresh.yml`."
        )
        title = f"🚨 Data stale — {len(stale)} file(s)"
        if open_issues:
            n = open_issues[0]["number"]
            gh("issue", "comment", str(n), "--repo", repo, "--body", body)
            print(f"commented on existing issue #{n}")
        else:
            # Try to create with label; create label first if needed (idempotent).
            gh("label", "create", LABEL, "--repo", repo, "--description", "Data refresh freshness", "--color", "fbca04")
            gh("issue", "create", "--repo", repo, "--title", title, "--body", body, "--label", LABEL)
            print("opened new freshness issue")
    else:
        # All fresh — close any open freshness issues.
        for issue in open_issues:
            n = issue["number"]
            gh("issue", "comment", str(n), "--repo", repo, "--body", "✅ All data files are fresh again. Auto-closing.")
            gh("issue", "close", str(n), "--repo", repo)
            print(f"closed stale-resolved issue #{n}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
